### ISSUE TITLE
Bug: iframe not full width when multiple instances?

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#315]
**Note: The links stated below do not trigger the bug anymore. I have programmed a workaround via PHP. The bug, however, still exists!**

*Former Headline: "Appending an Image resizes SCeditor's iframe"* 
*Update: Behaviour not only on upload, see below.*

Situation: I have multiple instances of SCEditor on my page. Example: http://www.q2apro.com/forum/74/sceditor-with-mobiles-test-post-q2a

If you click on comment and then on button Browse (to upload an image), jquery will upload the image immediately after the file has been chosen.

Problem now, after the successful uploaded, SCEditor resizes not only the image but also the iframe: 

![sceditor-bug](https://cloud.githubusercontent.com/assets/6764548/3565498/edaab082-0abc-11e4-8bd2-f079a873a515.png)

The web inspector shows me before the upload: 

`<iframe tabindex="0" style="width: 524px; height: 307px;" frameborder="0"></iframe>`

and after the image upload: 

`<iframe tabindex="0" style="width: 90px; height: 339px;" frameborder="0"></iframe>`

So something must be resing the editor's iframe. 

--- 

**Update:** Just now I realized that the hidden iframe is already resized when clicking on the "comment" button in my forum to fade in the editor. 

![iframe](https://cloud.githubusercontent.com/assets/6764548/3565511/85893d10-0abd-11e4-8c0e-e1edf9ee290c.png)

You can try it here, click on the comment button and **insert text** and you will notice it: http://www.q2apro.com/forum/74/sceditor-with-mobiles-test-post-q2a

What could be the bug?

Thanks,
Kai

PS: When resizing the entire browser window, the iframe seems to get updated and displays correctly.

**Comment by sphaero** [comment]
Similar problem here. Multiple instances inside the @jdorn/json-editor render a 92px wide iframe from the second on.

**Comment by samclarke** [comment]
I can reproduce this is if the editor is created on a hidden textarea and CSS is used to force the width (e.g.: https://jsfiddle.net/2bvjmywc/1/) or if it's created on a hidden textarea with a width of `100%` set (e.g.: https://jsfiddle.net/2bvjmywc/2/). I think that's what's happening here.

If it is then it's caused by the editor is trying to stay within the same bounds as the original textarea by measuring the width and height of the textarea and toolbar. Unfortunately it fails horribly if the textarea is hidden.

The toolbar height can vary so, to stay within the bounds of the original textarea, the height of the iframe needs to exclude the toolbar height. It's easy to do using flexbox (just 3 lines of CSS) but without flexbox the only solution is CSS tables. Unfortunately IE handles them slightly differently to other browsers and I couldn't find a way to make it work in IE.

The only solutions I can think of are:

1. Break backward compatibility and not include the toolbar in the editor height. That would mean the editor will take up more space than the original textarea.
2. Use flexbox and drop all browsers that don't support it (according to [Can I Use...](http://caniuse.com/#feat=flexbox) that means dropping IE <= 9). I'm not sure I want to drop IE 9 support plus it looks like flexbox is buggy in IE.
3. Do nothing and leave this bug

None of which are ideal. If anyone can think of a better solution I'm happy to try it.

**Comment by brunoais** [comment]
My suggestion:
Document it breaks (give a link to this issue too) and...
... let it break in IE<=9.
OR
... make a behavior (worked for me in the past).

There's no viable way of solving it in IE<=9. Also, I've tried behaviors and... although they are a hack all in itself, they actually work to solve these issues. Do note they are specific to IE and they were discontinued in IE10.
Also, I don't think IE10 has any bugs in flexbox that affects this.

**Comment by samclarke** [comment]
An IE behavior sounds like a great solution! I can only find an ancient page on [MSDN describing them](https://msdn.microsoft.com/en-us/library/ms537634(v=vs.85).aspx). Do you know if they can they detect when the visibility or height of a node has changed? If they can then we can switch to flexbox and use a behavior for IE9 compatibility.

> Also, I don't think IE10 has any bugs in flexbox that affects this.

I've just tested it and it seems to works without a problem so just depends on IE 9 now.

**Comment by brunoais** [comment]
It's a [behavior](https://msdn.microsoft.com/en-us/library/ms530723(v=vs.85).aspx) not an [expression](https://msdn.microsoft.com/en-us/library/ms537634(v=vs.85).aspx)
Height/width change, yes.
Gaining and losing visibility, no.
Calculating original size at creation, yes.
It is basically javascript and you can make your own event listeners, anyway.
Just be careful to avoid attaching repeated event listeners to the same thing.

**Comment by samclarke** [comment]
>Gaining and losing visibility, no.

That might be a problem. Won't it will suffer from the same issue as above if it's hidden when created?

If it does then it would mean having to drop IE 9 support to fix this issue or find another solution.

**Comment by brunoais** [comment]
@samclarke 
If there's anything that requires a recalculation of a CSS rule, the behavior will be called for its own calculation on the subject. Just try it anyway. It's easy to do a poc for IE behaviors. What isn't is to make the robust for production.

**Comment by samclarke** [comment]
I've tried it seems to have the same issue as above. Could be down to my poor implementation though. On the plus side I have discovered the [propertychange](https://msdn.microsoft.com/en-gb/library/ms536956(v=vs.85).aspx) event gets triggered on style changes so we could add an propertychange event listener to all the parents elements and if the changed property is style.display then recalculate.

Only issues are that it might not work well with resizing (that's easy to check) and it's going to be a lot of work to get right and debug. So I guess the question now is how important is IE 9 support? Is it worth all that effort or would it be better to just fix other bugs and either leave this one or dump IE 9 support.

**Comment by brunoais** [comment]
For resizing, just listen to to the resize event on the parent element.

**Comment by samclarke** [comment]
Yeah thinking about it, the editor already handles resizing and I can't see there being a conflict with the propertychange event so that should be OK. Just leaves the question of whether it's worth it.

The current IE 9 usage stats are:

[Wikimedia](https://stats.wikimedia.org/wikimedia/squids/SquidReportClients.htm):
IE 8 - 1.28% & 1.31%
IE 9 - 1.37% & 1.28%

[Statcounter](http://gs.statcounter.com/#browser_version_partially_combined-ww-monthly-201508-201608-bar)
IE 8 - 1.57%
IE 9 - 1.19%

[data.gov.uk](https://data.gov.uk/data/site-usage?month=2016-09#browsers_versions)
IE 8 - 0.56%
IE 9 - 1.04%

[Netmarketshare IE 8](https://www.netmarketshare.com/report.aspx?qprid=3&qpaf=&qpcustom=Microsoft+Internet+Explorer+8.0&qpcustomb=0&qpsp=200&qpnp=13&qptimeframe=M) - 3.65%
[Netmarketshare IE 9](https://www.netmarketshare.com/report.aspx?qprid=3&qpaf=&qpcustom=Microsoft+Internet+Explorer+9.0&qpcustomb=0&qpsp=200&qpnp=13&qptimeframe=M) - 4.83% (seems to be going up?)

If all the code can go in a behavior (I'm assuming they can add event listeners to parents?) then at least it won't increase the code size or cause issues for other browsers.

**Comment by brunoais** [comment]
I can't answer you that, unfortunately. You can leave it to someone else to implement if they require it for their website. It is only 1% of the users on most websites and it only happens if the replacing textarea was hidden.

**Comment by samclarke** [comment]
The IE behavior seems to work surprisingly well. I was expecting that to take a huge amount of debugging.

Did hit an IE flexbox bug though. IE doesn't expand the iframe to fill the full width so have to use `calc()` to fix that but looks like it works well apart from that.
