### ISSUE TITLE
Any way to develop SCEditor without Grunt?

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#365]
Hi Sam, I would like to fix some bugs of SCEditor. Problem is I have never used grunt and the [setup process](http://gruntjs.com/getting-started) seems not that easy.

Is there any way I can grab the js-files and run the javascript locally? I mean, without installing a server etc. Just using the pure JS code?

I guess I have to embed the scripts from the `src` folder instead of the minified version?

**Comment by samclarke** [comment]
You can test changes without a build step by using `/tests/manual/debug/index.html`. The unit tests will also load the source without a build step.

The only issue is they will need to be loaded from a server. If you don't have one setup you can use `http-server` to do it:

    npm install http-server -g

and then from the root directory do:

    http-server ./ -p2222

You can then manually test changes by going to http://localhost:2222/tests/manual/debug/ or run the unit tests by going to http://localhost:2222/tests/unit/.

You'ill also need to setup dev tools to not cache while open otherwise any changes won't be loaded.
