### ISSUE TITLE
Why does SCEditor always start with <p> 	<br /> </p>?

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#371]
@samclarke When you start SCEditor and look to the HTML source, you find: 

```
<p>
    <br />
</p>
```

Even when you write text, the `<br />` is always in the end of the text, right before the closing `</p>`.

From what I know, the `<br />` is unnecessary since p-tags are block elements and break anyways. 

What reason is behind this br-decision?

Thank you.

**Comment by samclarke** [comment]
Without the `<br/>` the `<p>` tag would be collapsed (0px height) so in order for the lines to match the output visually they need to have a `<br>` tag.

**Comment by q2apro** [comment]
Regarding the `br` tag: 

> line breaks are intended to be used in situations where the break must occur within the flow of text, such as in a poem.

From http://stackoverflow.com/q/12552978/1066234

Solution should be by CSS only! See http://stackoverflow.com/a/18249744/1066234

> Generally, <br/> is an indication of poor semantic HTML.

I would suggest adding to the editor CSS: 

    p {
      min-height: 1;
   }

> The recommended method for defining line height is using a number value, referred to as a "unitless" line height. A number value can be any number, including a decimal-based number, as is used in the first code example on this page.

**Comment by samclarke** [comment]
`min-height` is used but the `<br>` is still needed as sometimes hitting enter only inserts a single `<br>` which has no visual effect because the element was not visually collapsed thanks to the `min-height` style. You're right though, this isn't very semantic.

Luckily the extra `<br>` tags are only needed during editing so the xhtml plugin can remove them. In the case of `<p><br></p>` it would have to be replaced with something like `<p>&nbsp;</p>`. If the `<br>` was just removed the paragraph would appear collapsed making the output not match the editor visually.

SCEditor could require devs to add a `min-height` and just output empty `<p>` tags but that isn't really semantic either as it's still using `<p>` for presentation rather than content:

> As a general rule, elements whose content model allows any flow content or phrasing content should have at least one node in its contents that is palpable content and that does not have the hidden attribute specified.
https://www.w3.org/TR/html5/dom.html#palpable-content
> We discourage authors from using empty P elements. User agents should ignore empty P elements.
https://www.w3.org/TR/WD-html40-970917/struct/text.html

The most semantic way would be to remove the paragraph and have the element below/above add a bigger margin. That requires knowing the line-height of the surrounding contents and results in inline styles which are ugly (if the line-height changes, they all need to be modified which is worse IMHO).

I've had a look to see if other editors have a better solution and they all either output `<p><br></p>` or `<p>&nbsp;</p>` for empty lines. Neither of which is semantic although `<p>&nbsp;</p>` might be a bit more semantic. It adda spaces to empty lines when the text is copied though so results in a slightly worse UX.
