### ISSUE TITLE
Problem with pasting color content within a [color] [/color] tag

### ISSUE THREAD

**Issue by bhutaninitin** [samclarke/SCEditor#389]
I am reporting a use-case which I believe is a bug. Suppose I have something like the following:

[color=#ff3366] Hello World. [/color]
When I copy Hello and paste it between Hello and World, it appear as:

[color=#ff3366]Hello [/color][color=#ff3366]Hello [/color][color=#ff3366]World. [/color]

I think it should appear as which make the source more readable.

[color=#ff3366]Hello Hello World. [/color]

Regards,
Nitin

**Comment by brunoais** [comment]
Although annoying for who reads and edits the source code. I don't think this is a bug.
Something could be done about that, though. Personally, I think something should be done about that to ease both BBCode processing and readability.

**Comment by samclarke** [comment]
It would be a good thing to implement but I'm not completely sure how safe it is to merge identical nodes. As long as both nodes are inline it should be OK but I'm not 100% sure.

For instance, one of the unit tests now fails because of this. Currently when given a quote with multiple authors in `<cite>` tags it uses the first and treats any others as normal text.

So this:

    <blockquote>
        <cite>admin</cite>
        <cite>this should be ignored</cite> Testing 1.2.3....
    </blockquote>

Will currently produce this:

    [quote=admin]this should be ignored Testing 1.2.3....[/quote]

But with merging both cite tags are combined resulting in this:

    [quote=adminthis should be ignored] Testing 1.2.3....[/quote]

This particular case doesn't matter too much as it's questionable which makes more sense. But it is possible there could be other things like this where merging wouldn't make sense so it would need testing/investigating some more.

Merging the BBCode after it's been converted from the DOM would require knowing explicitly which tags can be merged so doing it in the DOM is probably a better idea.

**Comment by brunoais** [comment]
IMO, it should be part of the tag's options.
"May two similar HTML tags, next to each other, be merged?"
Maybe (for the option name):
"MergeAdjacentSimilarTags"

**Comment by samclarke** [comment]
Yes I think adding it in as optional is probably the best idea.

I think maybe do what paste filtering currently does and have an experimental `enableTagMerging` option until it's been tested thoroughly and then just enable it after more testing.

**Comment by bhutaninitin** [comment]
Hi..Is this enhancement there in V1.5?

**Comment by samclarke** [comment]
This is fixed by #804.
