### ISSUE TITLE
How to get an uncompressed version

### ISSUE THREAD

**Issue by brunoais** [samclarke/SCEditor#398]
How do I do to get an uncompressed version of SCE for testing and code checking purposes?

**Comment by samclarke** [comment]
If it's just to test out a change then you can use `tests/manual/debug` which will load the raw source code (might get cached by browser though).

To create the uncompressed release code you need to run:

    grunt release

which should create a ZIP containing both the uncompressed and and compressed versions.

**Comment by brunoais** [comment]
Where is it placed at?

**Comment by samclarke** [comment]
It's this file `https://github.com/samclarke/SCEditor/blob/master/tests/manual/debug/index.html`.

One thing I forgot to mention is it can't be loaded locally via `file:///` because if it is then Less.js won't be able to load the .less theme. `http-server` works perfectly though so if you don't already have a local server for testing you can use that.

    npm install http-server -g

then from the SCEditor directory:

    http-server -c-1

It should then be located at `http://127.0.0.1:8080/tests/manual/debug/`.

**Comment by brunoais** [comment]
So you mean that you didn't make any way of just join the files and not minimize?
Is there a way to make it also output without the minimization? That is what I want.
Also, port 8080 on my computer is already in use and removing its use is not an easy task.

**Comment by samclarke** [comment]
No but could be added fairly easily if you need it.

The files are in AMD format (well CJS wrapped in AMD) so they can be loaded via an AMD loader without joining them. The `tests/manual/debug` page already has everything set up though so if you just want to do a quick test it's probably easier to just use that.

You can change the port via the `-p` option: `http-server -c-1 -p4242`.

**Comment by brunoais** [comment]
For my objective... not that useful.
It is also not meant for a quick test either. Anyway... I'll try going by changing the port and moving on...

**Comment by samclarke** [comment]
I can always add an option to grunt to generate an uncompressed version if you need it. It's exactly the same as generating the minified version just without the minification.

**Comment by brunoais** [comment]
Yes please.
