### ISSUE TITLE
Undo plugin not work correctly with japanese language (Microsoft IME)

### ISSUE THREAD

**Issue by martec** [samclarke/SCEditor#457]
See detail in http://community.mybb.com/thread-172160.html

Problem occur in Chrome with undo plugin.

Ps. IME is Input method used in Windows to japanese language.

**Comment by brunoais** [comment]
IME is not only for Japanese, m8 ;). It is to allow typing in any language that does not use the alphabet used in most western countries. Chinese, Korean, Japanese, etc... rely on IME (or similar) to type those. If this is true, then it means that SCE with the undo plugin or any plugin that relies in the plugin interface won't work.

What we need to do now, is to check if the issue is really the undo plugin or SCE's plugin interface. Most likely  it is SCE's plugin interface because the undo plugin doesn't do anything to change the editor's text unless any of `ctrl+z`, `ctrl+shift+z` or `ctrl+y` key combos are pressed.

On the other hand, that error is actually quite odd to be specific to SCE because nowhere in the stack trace SCE appears... I'll try using IME myself with the undo plugin and see what I can come up with.

**Comment by samclarke** [comment]
One possibility is the editors `valueChanged` event which IIRC it doesn't handle `input` or composition events which are fired during IME input. That should only stop the undo plugin from adding to the undo stack though, not cause anything to disappear.

It looks like the IME input is being cancelled which is what's causing it to disappear. I have a suspicion that it's because markers are being inserted by the `valueChanged` event which might be enough to cause the input to be cancelled. Inserting markers shouldn't affect the selection and thus shouldn't affect the input but I can't see anything else which could be causing it.

If it turns out that is the cause then it's easy enough to fix, just don't trigger the  `valueChanged` event between the browsers `compositionStart` and `compositionEnd` events.

We'll need a way to test it though. I think the IME software used in the gif is the [Google Japanese Input](https://www.google.co.jp/intl/ja/ime/) but I have no idea how to use. @brunoais were you able to reproduce this?

**Comment by brunoais** [comment]
Tested on:
Firefox 38, Chrome 43, IE11 and Opera 12.17.
I can reproduce on Chrome. It is working on all others.
I've tried both typing some random text and also only `あ`'s. It was indifferent.
The timings were matching with `.valueChanged()` callback timings.
Sounds like if the HTML is changed (in this case, because of the marker placement) while typing with the IME in Chrome, the typing session is canceled.

Yes, not triggering the `valueChanged` event between the browser's `compositionStart` and `compositionEnd` sounds like the best choice... Maybe it could provide it as a service of some sort to place a stop for most actions (maybe even ignore commands input) while it is on composition mode. Regardless of that possibility, this should be a way to start.
