### ISSUE TITLE
Seems not to work in jQuery 3

### ISSUE THREAD

**Issue by prclx323800** [samclarke/SCEditor#525]
Hello,
SCEditor seems not to work in jQuery 3. At this time the latest version of jQuery is **3.1.0**. Both this version and **3.0.0** can not work with SCEditor. However, **2.2.4**, the latest version of 2.x, is ok.
In case you need, my browser is Chrome 51 and my OS Win 7. The console log shows

> Uncaught TypeError: a.indexOf is not a function

I do hope SCEditor would be compatible with jQuery 3.x soon.

**Comment by brunoais** [comment]
In which line of code does that happen?

**Comment by iam1me** [comment]
I also saw this error when initially attempting to setup SCEditor with JQuery 3. I also switched to JQuery 2 and it started working OK. The console doesn't give the line no. unfortunately. And since I was using the minified version of the sceditor script(s) it wouldn't have been helpful. After a little digging I found a StackOverflow thread that addresses at least one possible cause for this issue: http://stackoverflow.com/questions/37738732/jquery-3-0-url-indexof-error

Any calls to load, unload, and error have been deprecated since 1.8 and need to be changed to use the .on function instead. This, apparently, fixes the issue.

**Comment by brunoais** [comment]
Sounds like an easy fix problem. If you are able to fix it and do a pull request, it would be quite useful and you'd get credit for it. Otherwise, I may be able to do such change in the weekend.

**Comment by iam1me** [comment]
Sure I'll give it a shot. I might not be able to get to it till this weekend myself however.

**Comment by iam1me** [comment]
I tested it out, just doing some quick replaces for the .load, .bind, and .unbind functions (didn't see any others in there) and it was able to work with the JQuery 3 CDN without any immediate error. I'll put together a branch and pull request once I've had time to test it a bit more and make sure nothing breaks while using it

**Comment by iam1me** [comment]
It was a pretty small change overall. I also updated the example/example.html page to use the JQuery3 CDN. see #532
