### ISSUE TITLE
keyUp event binding is not working.

### ISSUE THREAD

**Issue by agungsijawir** [samclarke/SCEditor#542]
simply to make binding `keyUp()` / `keyPress()` / `keyDown()` gives me error:
```
jquery.sceditor.js:3116 Uncaught TypeError: base.on is not a function
    at SCEditor.base.keyUp (http://myapp.local/public/js/plugins/sceditor/jquery.sceditor.js:3116:17)
    at <anonymous>:1:37
```

code I am using is exact as on api docs. using version 1.5 (dev-uncompressed) and on Chrome latest version and firefox. 

Am I missing something? although other functions works properly.

**Comment by samclarke** [comment]
Just checked and it's caused by this commit 2f7e3150af4427c56ab7186eaabe910f4f3ec34f which updated from jQuery `bind()` to `on()`. Looks like it accidentally changed the SCEditor bind method as well. I'm not sure how this got passed the testing though.

This is quite a bad bug so I'll create another release with a fix as soon as it's tested. In the mean time using the `bind()` method should work.

**Comment by agungsijawir** [comment]
@samclarke thank you Sam!
