### ISSUE TITLE
v2.0.0 release

### ISSUE THREAD

**Issue by Eldenroot** [samclarke/SCEditor#580]
Hi @samclarke , is there any ETA for v2.0.0 release? It has been really long since last release, we really need a new version soon! :) Thank you very much!

**Comment by samclarke** [comment]
Currently the main thing blocking the v2 release is the new selection methods (#538) which I wanted to include. You're right though it has been ages since the last release and as they will need a lot of testing and will be backwards compatible it might be better to postpone them to v2.1.0 and get v2.0.0 released. I have some time tomorrow so I'll try give an ETA then.

**Comment by Eldenroot** [comment]
@samclarke - great, thank you fro your reply. There are many bug reports (MyBB software, uses old release) which were fixed by you in your unreleased version, it would be really nice to have an updated version soon.

**Comment by samclarke** [comment]
There are two backwards incompatible changes left to do before v2.0.0 is released which shouldn't take too long to do. I'm going to try release a beta version next weekend and as long as nothing major crops up v2.0.0 should be able to be released after that.
