### ISSUE TITLE
Code changes - Tags are processed twice

### ISSUE THREAD

**Issue by abetis** [samclarke/SCEditor#586]
Hello Sam,

I'm working on changes for list tags to allow different style (dot, square, circle, numeric, alphanumeric, roman...).
I've changed the UL tag to have style that will specify the type of the list.
Everything works fine beside that issue:
I add a list in the editor, switch to code view and the [ul] tag is added twice like that:
[ul=disc]
[ul=disc]
[li]text[/li]
[/ul]
[/ul]

While debugging that, I see that the following code is responsible for that:
```
	// code tags should skip most styles
	if (tag !== 'code') {
		// handle inline bbcodes
		curTag = handleStyles(node, curTag);
		curTag = handleTags(node, curTag);

		// handle blocklevel bbcodes
		curTag = handleStyles(node, curTag, true);
	}

	ret += handleTags(node, curTag, true);
```
Both the `handleStyles` and `handleTags` calls with blockLevel set to TRUE call the format of the UL tag, that adds the bbcode twice.

I don't think I understand the logic here...

Can you explain what do you mean by blocklevel bbcodes?
Why both `handleStyles` and `handleTags` should call the formatting of the tag?

Thanks.

**Comment by abetis** [comment]
Digging a bit more deeper I can see that block tag is considered one with isInline: false, which is what I have with the UL and OL tags.
Looking on other tags with isInline: false declaration I can see that none of them have both tags and styles declared, thats either tags with attributes or styles. 
That explains why I didn't see that behavior with other tags.
Is that restriction intentional? There is no tag that could have both?
In HTML5 most of the attributes moved to styling, but there are still some left, so I think there might be a case were you'd like to have both tag+attribute and a style defined.

Looking on handleStyles code I see another problem:
The code loops over all the styles and tries to match them to the element style, regardless whether the style belongs to the tag or not.
As I can see it, if there are 2 or more tags with style that have the same name, the code will not work properly and will catch the first tag in the list. Am I correct?

Thanks.

**Comment by samclarke** [comment]
Currently it's not possible to target tags combined with styles as they're treated separately. You can target a tag and then in the format method choose to handle it if it has the correct style or just return the contents and do nothing if it doesn't. That will do what you want but is a little more code.

> Can you explain what do you mean by blocklevel bbcodes?

In HTML there are [block level elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements) and [inline elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements). Because BBCode converts to HTML they can also be block level or inline.

As some BBCode parsers don't allow putting block level elements inside inline elements (as it results in invalid markup) SCEditor will try to convert the inlines first so the block level BBCodes can wrap them. It's not too important as SCEditor will tidy up the BBCode fixing any invalid nesting later on it just reduces the amount of fixing needed.

For example:

```bbcode
[b]outer
[quote]inner[/quote]
outer[/b]
```

would be invalid so SCEditor will convert it into:

```bbcode
[b]outer[/b]
[quote][b]inner[/b][/quote]
[b]outer[/b]
```

which is valid and what browsers do internally.

**Comment by abetis** [comment]
Thanks for the fast answer.
Will try to check in format function, probably will do the trick...

Still wonder why it can't be done in the `handleStyles` function.
I see that the tag is stored in the `stylesToBBCodes` array when the cache is build in the `buildBbcodeCache` function:
`	stylesToBBCodes[isBlock][style][bbcode] = values;
`
so it's probably possible to check it in the loop before calling the `format` function...

**Comment by samclarke** [comment]
It could be done, the whole conversion code could really do with a tidy up.

It might make sense to update the `tags` option to allow specifying styles to match like other attributes. The styles option could then be mapped to `*` tags to match any and the whole chunk of code could be simplified. I'll add an issue to look into updating it.
