### ISSUE TITLE
Edge not working with color change correctly

### ISSUE THREAD

**Issue by chrisbetson** [samclarke/SCEditor#636]
The change color function works in all browsers except Edge.
If you change color on a line, it works for that line but if you press 'enter' at the end of the line the next line is given a random color.
If you switch to source code and back again before pressing 'enter' the cursor disappears - clicking in the editor gives you focus again and if you then press 'enter' then the color is correct for as many times as you like unless you change the color again.

**Comment by samclarke** [comment]
Thanks for reporting!

After some testing this is an Edge bug that affects Edge 16 (current version) and has been fixed in Edge 17 (preview version).

Creating a workaround for this would be tricky, probably quite large and would require a lot of testing. Because of that I think that the best solution would be to wait for Edge 17 to be released as it should be soonish and the behaviour is still WYSIWYG (it's a weird behaviour but the output does match what you see).

If the bug was worse, the fix simpler or Edge 17 was likely to not be released soon I'd try add a fix for this. As it is though I think the best solution is to just leave this one.
