### ISSUE TITLE
Issue with Android autocomplete

### ISSUE THREAD

**Issue by yamikuronue** [samclarke/SCEditor#698]
I'm having a strange issue with autocomplete in my product's sceditor instances when I use my android phone. When I begin typing a few letters, such as "diri", and I click on the suggestion "dirigible", then the word "dirigible" is correctly entered into the editor. However, if I type something like "deri", and I click the suggestion "dirigible", it does not enter "dirigible"  but instead something like "deridirig". My hunch is that it's sending backspaces followed by "dirigible" and the backspaces are not being honored, or some weirdness like that, but it's never the full word -- it appears to stop at the right number of letters, regardless how far through the word it is. I am not certain this happens every time, either.

Have you seen this? Is there a workaround?  This is a Pixel 1 running Android 8.1 in the Chrome browser.

**Comment by samclarke** [comment]
Thanks for reporting! I've just been looking into this and it also happens with a [plain content editable div](https://jsfiddle.net/d4tuch41/) so it looks like an issue with Chrome for Android / Google keyboard. I couldn't find an issue about it so I've created a [new one here](https://bugs.chromium.org/p/chromium/issues/detail?id=838993).

Looking at the events that get fired it seems to be inserting the text and then sending the delete event which is messing things up. It doesn't happen every time, at least for me, just randomly.

Unfortunately, I don't think this can be fixed at this level. Knowing when the events are out of sync due to the bug and then working out what was supposed to happen would be hard and likely to cause far more bugs so I think this will have to be fixed in Chrome / Google keyboard.

**Comment by yamikuronue** [comment]
Thank you for investigating! I will follow that report instead.
