### ISSUE TITLE
Popups for buttons do not get the correct position in space (.offset() function problem)

### ISSUE THREAD

**Issue by nichierichetti** [samclarke/SCEditor#877]
Dear all,

another Issue I have on my forum, basically all the popups are not in the correct position... they appear randomly next to the editor.
Upon checking the js codes I noticed that the variable .offset() defines the position of the editor in the space and then creates the coordinates for the popups with inline css. But it does not seem to work for me, can I get some help?

The screenshot gives you an idea, but it's just one example among all.
This for example is the youtube popup (button on the right, popup somewhere more on the left)

<img width="759" alt="Schermata 2022-01-22 alle 16 40 07" src="https://user-images.githubusercontent.com/66752025/150645354-5e7b9350-08a8-4e83-99b6-d1f91c88badd.png">

**Comment by samclarke** [comment]
It looks like there is some conflicting CSS somewhere but without seeing the CSS on the page it's difficult to say what might be causing it.

Could you provide a link to your forum with the issue? If you don't want to share it publicly you can email me at sam@sceditor.com.

**Comment by nichierichetti** [comment]
Dear @samclarke 

I have sent you an email! Thanks in advance!

**Comment by samclarke** [comment]
Closing this as it should now be fixed.

If anyone else has this issue, this was caused by a CSS conflict with an old version of SCEditor which placed the drop downs in the body instead of as children of the editor container.

The best fix for this is to upgrade as there are also security fixes since then but if not possible, making sure the body isn't positioned or adding some CSS to move the dropdown to compensate should work. Another fix is to patch the createDropDown method to place the dropdown inside the editors container.
