### ISSUE TITLE
Bug - Firefox only - editor.getRangeHelper().selectedRange() returns undefined

### ISSUE THREAD

**Issue by huanacaraz** [samclarke/SCEditor#910]
The undo plugin initialization doesnt work in firefox, the problem is that in function updateLastState() the call to editor.getRangeHelper().selectedRange() returns undefined. In IE/Chrome it works OK

### Steps to reproduce the problem

1. enable undo plugin
2. initialize sceditor (I use it in BBcode)

For now I fixed it by checking the output and if it is undefined, just return the updateLastState function.

**Comment by samclarke** [comment]
Thanks for reporting!

The issue is being caused by Firefox returning `null` from `getSelection()` when the editors `iframe` is first created. During testing, it only seems to happen about half the time so it's not deterministic.

I've added a fix to the undo plugin here (https://github.com/samclarke/SCEditor/commit/16318b752aaba6efd0ee8bc0b9062ae18c8f86a0).
